####################################################################
# Apt update for UBuntu
####################################################################
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  when: ansible_distribution == 'Debian' 

- name: upgrade all packages
  apt:
    name: '*'
    state: latest
  when: ansible_distribution == 'Debian' 

####################################################################
# Update system for Centos
####################################################################
- name: Update system and add RHEL
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  when: ansible_distribution == 'CentOS'

####################################################################
#  Setup Timedatectl
####################################################################
- name: Set time to {{ timezone }}
  shell: timedatectl set-ntp on && timedatectl set-timezone {{ timezone }}

####################################################################
# Set hostname
####################################################################
- name: add hostname to /etc/hosts
  lineinfile:
   dest: /etc/hosts
   regexp: '^127\.0\.0\.1[ \t]+localhost'
   line: '127.0.0.1 localhost {{ inventory_hostname }} {{ inventory_hostname }}.{{ base_domain }}'
   state: present
- hostname:
   name: "{{ inventory_hostname }}.{{ base_domain }}"