####################################################################
# Set hostname
####################################################################
- name: Set hostname
  command: hostnamectl set-hostname {{ freeipa_hostname }}.{{ base_domain }}
- lineinfile:
    path: /etc/hosts
    line: '{{ ansible_default_ipv4.address }}    {{ freeipa_hostname }}.{{ base_domain }}'

####################################################################
#  Setup Timedatectl
####################################################################
- name: Set time to {{ timezone }}
  shell: timedatectl set-ntp on && timedatectl set-timezone {{ timezone }}

####################################################################
# Update system for Centos
####################################################################
- name: Update system and add RHEL
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  when: ansible_distribution == 'CentOS'

####################################################################
# Install/Setup FreeIPA
####################################################################
- name: Install IPAserver
  yum: name='{{ item }}' state=present
  with_items:
    - '*'
    - vim 
    - net-tools 
    - ipa-server 
    - ipa-server-dns
    - python-firewall

- name: Run the ipa-server-install command
  command: ipa-server-install -U --setup-dns --allow-zone-overlap --hostname={{ freeipa_hostname }}.{{ freeipa_domain }} --domain={{ freeipa_domain }} --realm={{ freeipa_realm_dc | upper }} --ds-password={{ freeipa_directory_password }} --admin-password={{ freeipa_admin_password }} --forwarder={{ freeipa_dns_server1 }} --forwarder={{ freeipa_dns_server2 }}
  register: ipa_result
  failed_when: "'IPA server is already configured on this system' in ipa_result.stdout"

####################################################################
#  Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Finished setting up FreeIPA server on {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"